name: Deploy branch environment
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create resource group
        shell: pwsh
        run: |
          $location = '${{ github.event.repository.name }}-${{ github.ref_name }}'.replace('/', '-')
          az login --use-device-code
          az group create --name $location --location uksouth

          az deployment group create `
          --name $location-deployment `
          --resource-group $location `
          --template-file EnvironmentTests\bicep\main.bicep