name: Deploy branch environment
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
          enable-AzPSSession: true
        - run: |
          $location = '${{ github.event.repository.name }}-${{ github.ref_name }}'.replace('/', '-')

          az group create --name $location --location uksouth

          $uniqueId = (New-Guid).Guid.replace('-', '')
          $password = ("!@#$%^&*0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".tochararray() | sort {Get-Random})[0..40] -join ''
          $json = Get-Content 'EnvironmentTests\bicep\main.parameters.json' | ConvertFrom-Json
          $json.parameters.uniqueId.value = $uniqueId
          $json.parameters.sqlServerPassword.value = $password
          $json | ConvertTo-Json | Out-File 'EnvironmentTests\bicep\main.parameters.json'

          az deployment group create `
          --name $location-deployment `
          --resource-group $location `
          --template-file EnvironmentTests\bicep\main.bicep